export const staff = [
    {
        order: 1,
        id: 1,
        name: 'Jane Doe',
        title: 'Controller',
        email: 'email@email.com',
        photo: 'cutchall_greg.jpeg',
    },
    {
        order: 2,
        id: 2,
        name: 'John Doe',
        title: 'Controller',
        email: 'email@email.com',
        photo: 'charleston_christine.jpeg',
    },
    {
        order: 3,
        id: 3,
        name: 'Lois Doe',
        title: 'Controller',
        email: 'email@email.com',
        photo: 'Abby_Binderup.jpeg',
    },
    {
        order: 4,
        id: 4,
        name: 'Stewart Doe',
        title: 'Controller',
        email: 'email@email.com',
        photo: 'deShawndra.jpeg',
    },
    {
        order: 5,
        id: 5,
        name: 'Peter Doe',
        title: 'Controller',
        email: 'email@email.com',
        photo: 'griggs_tim.jpeg',
    },
    {
        order: 6,
        id: 6,
        name: 'Ryan Ernst',
        title: 'Controller',
        email: 'email@email.com',
        photo: 'RyanErnst.jpeg',
    },
    {
        order: 7,
        id: 7,
        name: 'Ryan Ernst',
        title: 'Controller',
        email: 'email@email.com',
        photo: 'RyanErnst.jpeg',
    },
    {
        order: 8,
        id: 8,
        name: 'Ryan Ernst',
        title: 'Controller',
        email: 'email@email.com',
        photo: 'RyanErnst.jpeg',
    }
]
