/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_appsync_graphqlEndpoint": "https://q5atpfoxu5dgxgxnuj3napgvfe.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "da2-6n3xnmyn4neg5o4n6aft4g2qqm",
    "aws_cognito_identity_pool_id": "us-east-2:b28ae5ec-bd9e-45a1-82e2-a66c1fd9c5cf",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_RKZeEXF0E",
    "aws_user_pools_web_client_id": "5np54drjj607rmo4bdlf16fuqu",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": [
            "REQUIRES_LOWERCASE",
            "REQUIRES_NUMBERS",
            "REQUIRES_UPPERCASE"
        ]
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "cutchall231954-staging",
    "aws_user_files_s3_bucket_region": "us-east-2"
};


export default awsmobile;
